#!/bin/bash

DIR=~/.dotfiles
OLDDIR=~/.dotfiles_old
FILES=".bashrc .config .gitconfig .scripts .conkyrc"

echo "Creating Backups dir"
mkdir -p ~/.backups
echo "...done"

echo "Creating $OLDDIR for backup of any existing dotfiles in ~"
mkdir -p $OLDDIR
echo "...done"

echo "Changing to the $DIR directory"
cd $DIR
echo "...done"

for file in $FILES; do
    echo "Moving dotfiles from $file to $OLDDIR"
    mv ~/$file $OLDDIR/
    echo "Creating symlink to $file in home directory."
    ln -s $DIR/$file ~/$file
done
